# Generated by Django 4.1.3 on 2022-12-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message_model',
            old_name='me',
            new_name='receiver',
        ),
        migrations.AddField(
            model_name='message_model',
            name='sender',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
