# Generated by Django 4.1.3 on 2022-12-31 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_chat', '0002_rename_me_message_model_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='room_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='my_chat.message_model'),
        ),
    ]
