# Generated by Django 4.1.3 on 2023-01-05 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_chat', '0004_video_call'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video_call',
        ),
    ]
