# Generated by Django 4.1.3 on 2023-01-05 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rduser', '0002_remove_customer_g_post_remove_customer_group'),
        ('my_chat', '0006_video_call'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video_call',
            new_name='Calls',
        ),
    ]
