# Generated by Django 4.1.3 on 2023-01-05 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rduser', '0002_remove_customer_g_post_remove_customer_group'),
        ('my_chat', '0007_rename_video_call_calls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calls_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rduser.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='Calls',
        ),
    ]
