# Generated by Django 4.1.3 on 2023-01-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_chat', '0009_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calls_video',
            name='username',
        ),
        migrations.DeleteModel(
            name='Check',
        ),
        migrations.DeleteModel(
            name='Calls_video',
        ),
    ]
