# Generated by Django 4.1.3 on 2022-12-15 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('admin', models.CharField(default=False, max_length=100)),
                ('members_count', models.IntegerField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='G_Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='frontend/src/post_images')),
                ('caption', models.TextField(default=False)),
                ('reported', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banned', models.BooleanField(default=False)),
                ('likes_for_post', models.IntegerField(default=0)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_to_group', to='group.group_model')),
            ],
        ),
        migrations.CreateModel(
            name='G_Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.g_posts')),
            ],
        ),
        migrations.CreateModel(
            name='G_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('user', models.CharField(max_length=100)),
                ('prof', models.CharField(default=False, max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_for', to='group.g_posts')),
            ],
        ),
    ]
