# Generated by Django 4.1.3 on 2023-01-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_g_posts_user_group_model_user_post_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='g_posts',
            name='file',
            field=models.FileField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='post_user',
            name='profile_pic',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
