# Generated by Django 4.1.3 on 2022-12-15 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=150, null=True)),
                ('verify_request', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('reported', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('followers', models.IntegerField(default=False)),
                ('following', models.IntegerField(default=False)),
                ('online', models.BooleanField(default=False)),
                ('profile_pic', models.FileField(default=False, upload_to='frontend/src/post_images')),
                ('string_pic', models.CharField(default=False, max_length=100)),
                ('password', models.CharField(max_length=150)),
                ('otp', models.CharField(blank=True, max_length=150, null=True)),
                ('g_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to='group.g_posts')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to='group.group_model')),
            ],
        ),
    ]
