# Generated by Django 4.1.3 on 2022-12-15 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rduser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='g_post',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='group',
        ),
    ]
