# Generated by Django 4.1.3 on 2023-01-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rduser', '0002_remove_customer_g_post_remove_customer_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
