# Generated by Django 4.1.5 on 2023-01-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rduser', '0003_alter_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.FileField(null=True, upload_to='frontend/src/post_images'),
        ),
    ]
