# Generated by Django 4.1.3 on 2023-01-07 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rduser', '0003_alter_customer_profile_pic'),
        ('home', '0003_calls_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calls_video',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls_for', to='Rduser.customer'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='file',
            field=models.FileField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='status_model',
            name='status',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
