# Generated by Django 4.1.5 on 2023-01-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_posts_file_alter_status_model_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='file',
            field=models.FileField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='status_model',
            name='status',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
